import React from 'react'
import {
  ShoppingBag,
  Factory,
  Users,
  HeartPulse,
  Cpu,
  GraduationCap,
  TreePine,
  Landmark,
  HandHeart,
} from 'lucide-react'

// 🔹 Categorias de cada ramo
const categoriasPorRamo = {
  comercio: {
    Varejo: [
      'Loja física',
      'E-commerce',
      'Supermercado',
      'Boutique',
      'Loja de conveniência',
      'Loja de departamentos',
      'Eletrônicos e informática',
      'Materiais de construção',
      'Móveis e decoração',
      'Papelaria',
      'Cosméticos e perfumaria',
      'Moda e acessórios',
    ],

    Atacado: [
      'Distribuidora',
      'Centro logístico',
      'Marketplace B2B',
      'Atacado de alimentos',
      'Atacado de bebidas',
      'Atacado de vestuário',
      'Atacado farmacêutico',
      'Atacado de materiais de construção',
    ],

    Alimentação: [
      'Restaurante',
      'Lanchonete',
      'Padaria',
      'Cafeteria',
      'Delivery',
      'Marmitaria',
      'Food truck',
      'Hamburgueria',
      'Pizzaria',
      'Sushi bar',
      'Sorveteria / Açaí',
    ],
  },
  industria: {
    Manufatura: [
      'Metalurgia',
      'Têxtil',
      'Alimentos e bebidas',
      'Automotiva',
      'Móveis e decoração',
      'Plásticos e borrachas',
      'Eletroeletrônicos',
      'Farmacêutica e cosméticos',
      'Papel e celulose',
      'Embalagens',
      'Confecção e moda',
      'Bebidas e laticínios',
    ],

    Distribuição: [
      'Produtos químicos',
      'Equipamentos industriais',
      'Insumos agrícolas',
      'Ferramentas e máquinas',
      'Materiais elétricos',
      'Peças automotivas',
      'Produtos hospitalares e laboratoriais',
      'Materiais para construção civil',
    ],

    Construção: [
      'Materiais de construção',
      'Cimento e concreto',
      'Pré-moldados',
      'Siderurgia',
      'Madeiras e serrarias',
      'Tintas e impermeabilizantes',
      'Estruturas metálicas',
      'Blocos e artefatos de concreto',
    ],
  },
  servicos: {
    Profissionais: [
      'Consultoria',
      'Contabilidade',
      'Jurídico',
      'Marketing',
      'Recursos Humanos (RH)',
      'Arquitetura e urbanismo',
      'Engenharia',
      'Psicologia e Terapias',
      'TI e Desenvolvimento de Software',
      'Design gráfico e UX/UI',
      'Assessoria empresarial',
    ],

    Pessoais: [
      'Salão de beleza',
      'Barbearia',
      'Academia',
      'Clínica estética',
      'Estúdio de pilates',
      'Estúdio de tatuagem',
      'Pet shop e banho & tosa',
      'Aulas particulares / cursos',
      'Fotografia e filmagem',
    ],

    'Logística e transporte': [
      'Transporte rodoviário de cargas',
      'Entregas urbanas',
      'Motofrete',
      'Armazéns e armazenagem',
      'Operadores logísticos',
      'Transporte de passageiros (van/ônibus)',
      'Distribuição de mercadorias',
      'Fretes e mudanças',
    ],

    Imobiliário: [
      'Corretora de imóveis',
      'Gestão de imóveis',
      'Condomínios',
      'Incorporação',
      'Administração de aluguéis',
      'Construtoras e loteadoras',
    ],
  },
  saude: {
    'Clínicas e consultórios': [
      'Clínica geral',
      'Odontologia',
      'Fisioterapia',
      'Psicologia',
      'Nutrição',
      'Dermatologia',
      'Ginecologia e Obstetrícia',
      'Ortopedia',
      'Pediatria',
      'Cardiologia',
      'Oftalmologia',
      'Endocrinologia',
      'Urologia',
      'Psiquiatria',
      'Clínicas de especialidades integradas',
    ],

    'Laboratórios e diagnósticos': [
      'Análises clínicas',
      'Imagem (Raio-X, Tomografia, Ressonância)',
      'Patologia',
      'Coletas e pontos de coleta',
      'Ultrassonografia',
      'Medicina nuclear',
      'Testes rápidos e triagem',
    ],

    'Hospitais e unidades médicas': [
      'Hospital geral',
      'Hospital especializado',
      'Pronto atendimento (UPA / emergência)',
      'Day clinic / cirurgias ambulatoriais',
      'Centros de reabilitação',
      'Unidades de terapia intensiva privadas',
      'Centros de hemodiálise',
    ],

    Farmacêutico: [
      'Farmácia',
      'Drogaria',
      'Manipulação',
      'Farmácias de atendimento 24h',
      'Farmácia clínica / consultório farmacêutico',
    ],
  },
  tecnologia: {
    'Desenvolvimento de software': [
      'SaaS',
      'Aplicativos',
      'ERP/CRM',
      'Soluções sob demanda',
      'Plataformas web',
      'E-commerce e marketplaces',
      'Integrações e APIs',
      'Automação de processos (RPA)',
    ],

    Infraestrutura: [
      'Cloud',
      'Hospedagem',
      'Redes e servidores',
      'Cybersegurança e proteção de dados',
      'DevOps e CI/CD',
      'Monitoramento e observabilidade',
      'Data centers',
    ],

    'Hardware e eletrônicos': [
      'Montagem de PCs',
      'Equipamentos IoT',
      'Automação residencial',
      'Manutenção de hardware',
      'Equipamentos industriais',
      'Robótica',
      'Wearables',
    ],

    'Startups e inovação': [
      'Fintech',
      'Healthtech',
      'Edtech',
      'Govtech',
      'Agrotech',
      'Logtech',
      'Retailtech',
      'Proptech',
      'Legaltech',
      'Hrtech',
      'Martech',
      'IA e Machine Learning',
    ],
  },
  educacao: {
    'Instituições formais': [
      'Escola',
      'Faculdade',
      'Universidade',
      'Centro técnico',
      'Educação infantil',
      'Ensino fundamental',
      'Ensino médio',
      'Escolas profissionalizantes',
      'Institutos de pesquisa',
    ],

    'Educação corporativa': [
      'Treinamentos',
      'Mentorias',
      'Desenvolvimento de liderança',
      'Workshops profissionais',
      'Programas de onboarding',
      'Capacitação interna',
      'Treinamentos em compliance',
      'Treinamentos técnicos',
    ],

    'Cursos livres': [
      'Idiomas',
      'Tecnologia',
      'Artes',
      'Culinária',
      'Música',
      'Fotografia',
      'Design',
      'Programação e TI',
      'Marketing digital',
      'Preparatórios (concursos, ENEM)',
      'Cursos online (EAD)',
    ],
  },
  agronegocio: {
    Produção: [
      'Agricultura',
      'Pecuária',
      'Hortifrutigranjeiros',
      'Grãos (soja, milho, trigo)',
      'Cafeicultura',
      'Avicultura',
      'Suinocultura',
      'Agroflorestal',
      'Aquicultura e piscicultura',
      'Cana-de-açúcar',
    ],

    'Indústria agro': [
      'Cooperativas',
      'Processamento de alimentos',
      'Distribuição agrícola',
      'Frigoríficos',
      'Laticínios',
      'Beneficiamento de grãos',
      'Armazenagem e silos',
      'Indústria de ração animal',
    ],

    'Serviços de apoio': [
      'Máquinas agrícolas',
      'Consultoria agronômica',
      'Insumos e fertilizantes',
      'Defensivos agrícolas',
      'Tecnologia agrícola (agtech)',
      'Irrigação e sistemas de água',
      'Transporte e logística agro',
      'Assistência técnica rural',
    ],
  },
  governo: {
    'Administração pública': [
      'Prefeituras',
      'Órgãos estaduais',
      'Entidades federais',
      'Câmaras municipais',
      'Tribunais e justiça',
      'Autarquias',
      'Secretarias municipais e estaduais',
      'Agências reguladoras',
      'Fundos e conselhos públicos',
    ],

    'Educação pública': [
      'Escolas municipais',
      'Escolas estaduais',
      'Institutos federais',
      'Universidades públicas',
      'Creches e educação infantil',
      'Centros de formação profissional pública',
      'Programas educacionais governamentais',
    ],

    'Saúde pública': [
      'UPAs',
      'Hospitais públicos',
      'Vigilância sanitária',
      'Postos de saúde (UBS)',
      'Centros de especialidades',
      'SAMU',
      'Laboratórios públicos',
      'Farmácia pública',
      'Centrais de regulação de saúde',
    ],
  },
  terceiroSetor: {
    'ONGs e Institutos': [
      'Assistência social',
      'Educação',
      'Meio ambiente',
      'Saúde',
      'Proteção animal',
      'Inclusão social',
      'Combate à fome',
      'Apoio a crianças e adolescentes',
      'Apoio a idosos',
      'Empoderamento feminino',
      'Tecnologia social',
      'Cultura e cidadania',
    ],

    Fundações: [
      'Cultura',
      'Esporte',
      'Direitos humanos',
      'Pesquisa e desenvolvimento',
      'Apoio à educação',
      'Promoção da saúde',
      'Desenvolvimento comunitário',
      'Preservação histórica',
    ],
  },
}

// 🔹 Soluções e métricas por ramo
const solucoesPorRamo = {
  comercio: {
    icone: <ShoppingBag size={36} color="#f7f7f7ff" />,
    titulo: 'Comércio',
    metricas: [
      'Vendas por período e por loja',
      'Ticket médio por cliente',
      'Produtos mais vendidos e curva ABC',
      'Margem de lucro por categoria',
      'Giro de estoque e ruptura',
      'Conversão de clientes (online e físico)',
      'CAC e LTV por canal',
      'Análise de sazonalidade e previsão de demanda',
      'Engajamento e recorrência de clientes',
    ],
    solucoes: [
      'Dashboard de vendas em tempo real',
      'Previsão de demanda com IA',
      'Gestão de estoque inteligente',
      'Relatórios automáticos de faturamento',
      'Painel de vendas por vendedor',
      'Análise de preço, concorrência e margem',
    ],
  },

  industria: {
    icone: <Factory size={36} color="#fefeffff" />,
    titulo: 'Indústria',
    metricas: [
      'Eficiência produtiva (OEE)',
      'Taxa de defeitos, retrabalho e desperdício',
      'Custo por unidade produzida',
      'Tempo de ciclo de produção (lead time)',
      'Produtividade por máquina e turno',
      'Nível de estoque de insumos e matéria-prima',
      'Consumo energético por linha de produção',
      'Previsão de demanda e planejamento (MRP)',
      'Paradas programadas vs. não programadas',
    ],
    solucoes: [
      'Análises de produtividade e manutenção preventiva',
      'Controle de custos de produção integrado ao ERP',
      'Dashboard de chão de fábrica em tempo real',
      'Planejamento e previsão de capacidade (PPCP)',
      'Monitoramento de qualidade e rastreabilidade',
    ],
  },

  servicos: {
    icone: <Users size={36} color="#f2f3f5ff" />,
    titulo: 'Serviços',
    metricas: [
      'Taxa de retenção de clientes',
      'Satisfação e NPS',
      'Tempo médio de atendimento (TMA)',
      'Receita por tipo de serviço e por profissional',
      'Taxa de agendamentos e comparecimentos',
      'Capacidade vs. demanda',
      'Custo por atendimento',
      'Taxa de recorrência e fidelização',
    ],
    solucoes: [
      'Agendamento inteligente e gestão de agenda',
      'Painel de performance de atendimentos',
      'Relatórios automáticos de faturamento e feedback',
      'Análise de produtividade por profissional',
      'Monitoramento de SLA e qualidade do atendimento',
    ],
  },

  saude: {
    icone: <HeartPulse size={36} color="#f3f5f7ff" />,
    titulo: 'Saúde',
    metricas: [
      'Taxa de comparecimento e faltas',
      'Tempo médio de espera e atendimento',
      'Produtividade de profissionais',
      'Receita por especialidade',
      'Taxa de ocupação de agendas',
      'Uso de salas e recursos',
      'Indicadores clínicos por especialidade',
      'Tempo de retorno do paciente',
    ],
    solucoes: [
      'Agenda médica automatizada com lembretes',
      'Relatórios de produtividade clínica',
      'Análise de cancelamentos e faltas de pacientes',
      'Painel de indicadores assistenciais',
      'Automação de registros e prontuários analíticos',
    ],
  },

  tecnologia: {
    icone: <Cpu size={36} color="#fefeffff" />,
    titulo: 'Tecnologia',
    metricas: [
      'Tempo médio de resolução de chamados (TMR/TMA)',
      'Retenção e churn de clientes SaaS',
      'Crescimento de usuários ativos (DAU/MAU)',
      'MRR e ARR (Receita recorrente)',
      'Custo por usuário ativo',
      'Uptime e SLA de sistemas',
      'Conversão no funil do produto',
      'Adoção de funcionalidades',
    ],
    solucoes: [
      'Monitoramento de performance de sistemas',
      'Análise de churn e comportamento de usuários',
      'Relatórios de suporte técnico e SLA',
      'Painel de crescimento SaaS',
      'Heatmaps e análises de uso do produto',
    ],
  },

  educacao: {
    icone: <GraduationCap size={36} color="#eef2f7ff" />,
    titulo: 'Educação',
    metricas: [
      'Taxa de evasão e retenção de alunos',
      'Desempenho médio por turma e disciplina',
      'Satisfação dos alunos (NPS)',
      'Taxa de aprovação e reprovação',
      'Assiduidade e frequência',
      'Receita por curso e modalidade',
      'Produção acadêmica (instituições superiores)',
      'Engajamento em plataformas EAD',
    ],
    solucoes: [
      'Painel de acompanhamento acadêmico',
      'Automação de feedbacks e avaliações',
      'Análises preditivas de evasão',
      'Relatórios automáticos de desempenho',
      'Dashboards para coordenadores e professores',
    ],
  },

  agronegocio: {
    icone: <TreePine size={36} color="#f3f5f7ff" />,
    titulo: 'Agronegócio',
    metricas: [
      'Produtividade por hectare',
      'Custo por safra e por animal',
      'Índice de conversão alimentar',
      'Projeções de safra',
      'Controle de insumos e fertilizantes',
      'Volume de produção por cultura',
      'Preços de mercado e commodities',
      'Eficiência de máquinas e implementos',
      'Indicadores climáticos e impacto na produção',
    ],
    solucoes: [
      'Dashboard de produção agropecuária',
      'Monitoramento de máquinas e consumo',
      'Controle financeiro das safras',
      'Previsão de produtividade com dados climáticos',
      'Relatórios de cooperativas e cadeia produtiva',
    ],
  },

  governo: {
    icone: <Landmark size={36} color="#f3f5f7ff" />,
    titulo: 'Governo',
    metricas: [
      'Execução orçamentária e financeira',
      'Indicadores educacionais (IDEB, evasão, aprovação)',
      'Indicadores de saúde (atendimentos, leitos, espera)',
      'Transparência e gastos por secretaria',
      'Tempo de resposta de serviços públicos',
      'Indicadores sociais (assistência, demanda reprimida)',
      'Eficiência operacional de equipes e setores',
    ],
    solucoes: [
      'Painéis de gestão pública e transparência',
      'Relatórios automáticos para secretarias',
      'Monitoramento de indicadores sociais',
      'Painel integrado de saúde e educação',
      'Visualização de orçamento em tempo real',
    ],
  },

  terceiroSetor: {
    icone: <HandHeart size={36} color="#f3f5f7ff" />,
    titulo: 'Terceiro Setor',
    metricas: [
      'Impacto social por programa',
      'Número de beneficiados',
      'Custo por ação social',
      'Captação vs. execução de recursos',
      'Transparência e prestação de contas',
      'Engajamento de voluntários',
      'Indicadores de sustentabilidade dos projetos',
    ],
    solucoes: [
      'Painel de impacto social',
      'Relatórios automáticos para financiadores',
      'Mapeamento geográfico de ações sociais',
      'Gestão de projetos e indicadores sociais',
      'Painel de captação de recursos',
    ],
  },
}
// 🔹 Exportação unificada
const DadosPorRamo = { categoriasPorRamo, solucoesPorRamo }

export default DadosPorRamo
